name: Build

on:
  push:
    branches: [ release ]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        app-name:
          - ShadowAI
        os:
          - macos-15-intel
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.SOURCE_REPO_PAT }}
          repository: ${{ secrets.SOURCE_REPO }}
          ref: main

      - uses: ./.github/actions/build
        id: build
        with:
          os: ${{ matrix.os }}
          app-name: ${{ matrix.app-name }}
          token: ${{ secrets.SOURCE_REPO_PAT }}

      - uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ steps.build.outputs.version }}
          tag_name: v${{ steps.build.outputs.version }}
          files: |
            build/*.dmg
            build/*.zip